from flask import request, jsonify, Blueprint
from mongodb_connection_manager import MongoConnectionHolder
from datetime import datetime
import uuid


Labrador_Retriever_Male = [
    {
        "breed_name": "Labrador Retriever",
        "gender": "Male",
        "from_age": 0.0,
        "to_age": 1.0,
        "avg_height_min": 40.0,
        "avg_height_max": 50.0,
        "avg_weight_min": 10.0,
        "avg_weight_max": 20.0,
        "avg_drink": 0.8,
        "avg_food": 1.5,
        "pic_url": "String"
    },
    {
        "breed_name": "Labrador Retriever",
        "gender": "Male",
        "from_age": 1.0,
        "to_age": 2.0,
        "avg_height_min": 50.0,
        "avg_height_max": 58.0,
        "avg_weight_min": 20.0,
        "avg_weight_max": 30.0,
        "avg_drink": 1.0,
        "avg_food": 2.0,
        "pic_url": "String"
    },
    {
        "breed_name": "Labrador Retriever",
        "gender": "Male",
        "from_age": 2.0,
        "to_age": 3.0,
        "avg_height_min": 55.0,
        "avg_height_max": 60.0,
        "avg_weight_min": 25.0,
        "avg_weight_max": 35.0,
        "avg_drink": 1.2,
        "avg_food": 2.3,
        "pic_url": "String"
    },
    {
        "breed_name": "Labrador Retriever",
        "gender": "Male",
        "from_age": 3.0,
        "to_age": 4.0,
        "avg_height_min": 56.0,
        "avg_height_max": 61.0,
        "avg_weight_min": 26.0,
        "avg_weight_max": 36.0,
        "avg_drink": 1.3,
        "avg_food": 2.4,
        "pic_url": "String"
    },
    {
        "breed_name": "Labrador Retriever",
        "gender": "Male",
        "from_age": 4.0,
        "to_age": 5.0,
        "avg_height_min": 57.0,
        "avg_height_max": 62.0,
        "avg_weight_min": 27.0,
        "avg_weight_max": 36.5,
        "avg_drink": 1.3,
        "avg_food": 2.5,
        "pic_url": "String"
    },
    {
        "breed_name": "Labrador Retriever",
        "gender": "Male",
        "from_age": 5.0,
        "to_age": 6.0,
        "avg_height_min": 57.0,
        "avg_height_max": 62.0,
        "avg_weight_min": 27.0,
        "avg_weight_max": 37.0,
        "avg_drink": 1.4,
        "avg_food": 2.5,
        "pic_url": "String"
    },
    {
        "breed_name": "Labrador Retriever",
        "gender": "Male",
        "from_age": 6.0,
        "to_age": 7.0,
        "avg_height_min": 57.0,
        "avg_height_max": 62.0,
        "avg_weight_min": 27.0,
        "avg_weight_max": 37.0,
        "avg_drink": 1.4,
        "avg_food": 2.5,
        "pic_url": "String"
    },
    {
        "breed_name": "Labrador Retriever",
        "gender": "Male",
        "from_age": 7.0,
        "to_age": 8.0,
        "avg_height_min": 57.0,
        "avg_height_max": 62.0,
        "avg_weight_min": 27.0,
        "avg_weight_max": 37.0,
        "avg_drink": 1.3,
        "avg_food": 2.4,
        "pic_url": "String"
    },
    {
        "breed_name": "Labrador Retriever",
        "gender": "Male",
        "from_age": 8.0,
        "to_age": 9.0,
        "avg_height_min": 57.0,
        "avg_height_max": 62.0,
        "avg_weight_min": 26.0,
        "avg_weight_max": 36.0,
        "avg_drink": 1.2,
        "avg_food": 2.3,
        "pic_url": "String"
    },
    {
        "breed_name": "Labrador Retriever",
        "gender": "Male",
        "from_age": 9.0,
        "to_age": 10.0,
        "avg_height_min": 57.0,
        "avg_height_max": 62.0,
        "avg_weight_min": 25.0,
        "avg_weight_max": 35.0,
        "avg_drink": 1.1,
        "avg_food": 2.2,
        "pic_url": "String"
    }
]
Labrador_Retriever_Female = [
    {
        "breed_name": "Labrador Retriever",
        "gender": "Female",
        "from_age": 0.0,
        "to_age": 1.0,
        "avg_height_min": 38.0,
        "avg_height_max": 48.0,
        "avg_weight_min": 8.0,
        "avg_weight_max": 18.0,
        "avg_drink": 0.7,
        "avg_food": 1.3,
        "pic_url": "String"
    },
    {
        "breed_name": "Labrador Retriever",
        "gender": "Female",
        "from_age": 1.0,
        "to_age": 2.0,
        "avg_height_min": 48.0,
        "avg_height_max": 55.0,
        "avg_weight_min": 18.0,
        "avg_weight_max": 28.0,
        "avg_drink": 0.9,
        "avg_food": 1.8,
        "pic_url": "String"
    },
    {
        "breed_name": "Labrador Retriever",
        "gender": "Female",
        "from_age": 2.0,
        "to_age": 3.0,
        "avg_height_min": 52.0,
        "avg_height_max": 58.0,
        "avg_weight_min": 22.0,
        "avg_weight_max": 32.0,
        "avg_drink": 1.1,
        "avg_food": 2.0,
        "pic_url": "String"
    },
    {
        "breed_name": "Labrador Retriever",
        "gender": "Female",
        "from_age": 3.0,
        "to_age": 4.0,
        "avg_height_min": 53.0,
        "avg_height_max": 59.0,
        "avg_weight_min": 23.0,
        "avg_weight_max": 33.0,
        "avg_drink": 1.2,
        "avg_food": 2.1,
        "pic_url": "String"
    },
    {
        "breed_name": "Labrador Retriever",
        "gender": "Female",
        "from_age": 4.0,
        "to_age": 5.0,
        "avg_height_min": 54.0,
        "avg_height_max": 60.0,
        "avg_weight_min": 24.0,
        "avg_weight_max": 34.0,
        "avg_drink": 1.2,
        "avg_food": 2.2,
        "pic_url": "String"
    },
    {
        "breed_name": "Labrador Retriever",
        "gender": "Female",
        "from_age": 5.0,
        "to_age": 6.0,
        "avg_height_min": 54.0,
        "avg_height_max": 60.0,
        "avg_weight_min": 24.0,
        "avg_weight_max": 34.5,
        "avg_drink": 1.3,
        "avg_food": 2.2,
        "pic_url": "String"
    },
    {
        "breed_name": "Labrador Retriever",
        "gender": "Female",
        "from_age": 6.0,
        "to_age": 7.0,
        "avg_height_min": 54.0,
        "avg_height_max": 60.0,
        "avg_weight_min": 24.0,
        "avg_weight_max": 34.0,
        "avg_drink": 1.2,
        "avg_food": 2.1,
        "pic_url": "String"
    },
    {
        "breed_name": "Labrador Retriever",
        "gender": "Female",
        "from_age": 7.0,
        "to_age": 8.0,
        "avg_height_min": 54.0,
        "avg_height_max": 60.0,
        "avg_weight_min": 23.0,
        "avg_weight_max": 33.0,
        "avg_drink": 1.1,
        "avg_food": 2.0,
        "pic_url": "String"
    },
    {
        "breed_name": "Labrador Retriever",
        "gender": "Female",
        "from_age": 8.0,
        "to_age": 9.0,
        "avg_height_min": 54.0,
        "avg_height_max": 60.0,
        "avg_weight_min": 22.0,
        "avg_weight_max": 32.0,
        "avg_drink": 1.0,
        "avg_food": 1.9,
        "pic_url": "String"
    },
    {
        "breed_name": "Labrador Retriever",
        "gender": "Female",
        "from_age": 9.0,
        "to_age": 10.0,
        "avg_height_min": 54.0,
        "avg_height_max": 60.0,
        "avg_weight_min": 21.0,
        "avg_weight_max": 31.0,
        "avg_drink": 0.9,
        "avg_food": 1.8,
        "pic_url": "String"
    }
]
Golden_Retriever_Male = [
    {
        "breed_name": "Golden Retriever",
        "gender": "Male",
        "from_age": 0.0,
        "to_age": 1.0,
        "avg_height_min": 40.0,
        "avg_height_max": 50.0,
        "avg_weight_min": 9.0,
        "avg_weight_max": 19.0,
        "avg_drink": 0.8,
        "avg_food": 1.5,
        "pic_url": "String"
    },
    {
        "breed_name": "Golden Retriever",
        "gender": "Male",
        "from_age": 1.0,
        "to_age": 2.0,
        "avg_height_min": 50.0,
        "avg_height_max": 58.0,
        "avg_weight_min": 20.0,
        "avg_weight_max": 30.0,
        "avg_drink": 1.0,
        "avg_food": 2.0,
        "pic_url": "String"
    },
    {
        "breed_name": "Golden Retriever",
        "gender": "Male",
        "from_age": 2.0,
        "to_age": 3.0,
        "avg_height_min": 56.0,
        "avg_height_max": 61.0,
        "avg_weight_min": 28.0,
        "avg_weight_max": 36.0,
        "avg_drink": 1.3,
        "avg_food": 2.3,
        "pic_url": "String"
    },
    {
        "breed_name": "Golden Retriever",
        "gender": "Male",
        "from_age": 3.0,
        "to_age": 4.0,
        "avg_height_min": 57.0,
        "avg_height_max": 62.0,
        "avg_weight_min": 30.0,
        "avg_weight_max": 38.0,
        "avg_drink": 1.4,
        "avg_food": 2.4,
        "pic_url": "String"
    },
    {
        "breed_name": "Golden Retriever",
        "gender": "Male",
        "from_age": 4.0,
        "to_age": 5.0,
        "avg_height_min": 58.0,
        "avg_height_max": 63.0,
        "avg_weight_min": 32.0,
        "avg_weight_max": 40.0,
        "avg_drink": 1.4,
        "avg_food": 2.5,
        "pic_url": "String"
    },
    {
        "breed_name": "Golden Retriever",
        "gender": "Male",
        "from_age": 5.0,
        "to_age": 6.0,
        "avg_height_min": 58.0,
        "avg_height_max": 63.0,
        "avg_weight_min": 32.0,
        "avg_weight_max": 39.0,
        "avg_drink": 1.3,
        "avg_food": 2.4,
        "pic_url": "String"
    },
    {
        "breed_name": "Golden Retriever",
        "gender": "Male",
        "from_age": 6.0,
        "to_age": 7.0,
        "avg_height_min": 58.0,
        "avg_height_max": 63.0,
        "avg_weight_min": 31.0,
        "avg_weight_max": 38.0,
        "avg_drink": 1.2,
        "avg_food": 2.3,
        "pic_url": "String"
    },
    {
        "breed_name": "Golden Retriever",
        "gender": "Male",
        "from_age": 7.0,
        "to_age": 8.0,
        "avg_height_min": 58.0,
        "avg_height_max": 63.0,
        "avg_weight_min": 30.0,
        "avg_weight_max": 37.0,
        "avg_drink": 1.1,
        "avg_food": 2.2,
        "pic_url": "String"
    },
    {
        "breed_name": "Golden Retriever",
        "gender": "Male",
        "from_age": 8.0,
        "to_age": 9.0,
        "avg_height_min": 58.0,
        "avg_height_max": 63.0,
        "avg_weight_min": 29.0,
        "avg_weight_max": 36.0,
        "avg_drink": 1.0,
        "avg_food": 2.0,
        "pic_url": "String"
    },
    {
        "breed_name": "Golden Retriever",
        "gender": "Male",
        "from_age": 9.0,
        "to_age": 10.0,
        "avg_height_min": 58.0,
        "avg_height_max": 63.0,
        "avg_weight_min": 28.0,
        "avg_weight_max": 35.0,
        "avg_drink": 0.9,
        "avg_food": 1.9,
        "pic_url": "String"
    }
]
Golden_Retriever_Female=[    
    {
        "breed_name": "Golden Retriever",
        "gender": "Female",
        "from_age": 0.0,
        "to_age": 1.0,
        "avg_height_min": 38.0,
        "avg_height_max": 48.0,
        "avg_weight_min": 8.0,
        "avg_weight_max": 18.0,
        "avg_drink": 0.7,
        "avg_food": 1.4,
        "pic_url": "String"
    },
    {
        "breed_name": "Golden Retriever",
        "gender": "Female",
        "from_age": 1.0,
        "to_age": 2.0,
        "avg_height_min": 48.0,
        "avg_height_max": 55.0,
        "avg_weight_min": 18.0,
        "avg_weight_max": 27.0,
        "avg_drink": 0.9,
        "avg_food": 1.8,
        "pic_url": "String"
    },
    {
        "breed_name": "Golden Retriever",
        "gender": "Female",
        "from_age": 2.0,
        "to_age": 3.0,
        "avg_height_min": 53.0,
        "avg_height_max": 58.0,
        "avg_weight_min": 24.0,
        "avg_weight_max": 32.0,
        "avg_drink": 1.2,
        "avg_food": 2.1,
        "pic_url": "String"
    },
    {
        "breed_name": "Golden Retriever",
        "gender": "Female",
        "from_age": 3.0,
        "to_age": 4.0,
        "avg_height_min": 54.0,
        "avg_height_max": 59.0,
        "avg_weight_min": 25.0,
        "avg_weight_max": 33.0,
        "avg_drink": 1.3,
        "avg_food": 2.2,
        "pic_url": "String"
    },
    {
        "breed_name": "Golden Retriever",
        "gender": "Female",
        "from_age": 4.0,
        "to_age": 5.0,
        "avg_height_min": 55.0,
        "avg_height_max": 59.0,
        "avg_weight_min": 26.0,
        "avg_weight_max": 34.0,
        "avg_drink": 1.3,
        "avg_food": 2.3,
        "pic_url": "String"
    },
    {
        "breed_name": "Golden Retriever",
        "gender": "Female",
        "from_age": 5.0,
        "to_age": 6.0,
        "avg_height_min": 55.0,
        "avg_height_max": 59.0,
        "avg_weight_min": 26.0,
        "avg_weight_max": 33.0,
        "avg_drink": 1.2,
        "avg_food": 2.2,
        "pic_url": "String"
    },
    {
        "breed_name": "Golden Retriever",
        "gender": "Female",
        "from_age": 6.0,
        "to_age": 7.0,
        "avg_height_min": 55.0,
        "avg_height_max": 59.0,
        "avg_weight_min": 25.0,
        "avg_weight_max": 32.0,
        "avg_drink": 1.1,
        "avg_food": 2.1,
        "pic_url": "String"
    },
    {
        "breed_name": "Golden Retriever",
        "gender": "Female",
        "from_age": 7.0,
        "to_age": 8.0,
        "avg_height_min": 55.0,
        "avg_height_max": 59.0,
        "avg_weight_min": 24.0,
        "avg_weight_max": 31.0,
        "avg_drink": 1.0,
        "avg_food": 2.0,
        "pic_url": "String"
    },
    {
        "breed_name": "Golden Retriever",
        "gender": "Female",
        "from_age": 8.0,
        "to_age": 9.0,
        "avg_height_min": 55.0,
        "avg_height_max": 59.0,
        "avg_weight_min": 23.0,
        "avg_weight_max": 30.0,
        "avg_drink": 0.9,
        "avg_food": 1.9,
        "pic_url": "String"
    },
    {
        "breed_name": "Golden Retriever",
        "gender": "Female",
        "from_age": 9.0,
        "to_age": 10.0,
        "avg_height_min": 55.0,
        "avg_height_max": 59.0,
        "avg_weight_min": 22.0,
        "avg_weight_max": 29.0,
        "avg_drink": 0.8,
        "avg_food": 1.8,
        "pic_url": "String"
    }
]
Beagel_Male = [{
        "breed_name": "Beagle",
        "gender": "Male",
        "from_age": 0.0,
        "to_age": 1.0,
        "avg_height_min": 30.0,
        "avg_height_max": 38.0,
        "avg_weight_min": 3.5,
        "avg_weight_max": 8.0,
        "avg_drink": 0.5,
        "avg_food": 1.0,
        "pic_url": "String"
    },
    {
        "breed_name": "Beagle",
        "gender": "Male",
        "from_age": 1.0,
        "to_age": 2.0,
        "avg_height_min": 38.0,
        "avg_height_max": 41.0,
        "avg_weight_min": 8.0,
        "avg_weight_max": 12.0,
        "avg_drink": 0.6,
        "avg_food": 1.2,
        "pic_url": "String"
    },
    {
        "breed_name": "Beagle",
        "gender": "Male",
        "from_age": 2.0,
        "to_age": 3.0,
        "avg_height_min": 40.0,
        "avg_height_max": 43.0,
        "avg_weight_min": 9.0,
        "avg_weight_max": 14.0,
        "avg_drink": 0.7,
        "avg_food": 1.4,
        "pic_url": "String"
    },
    {
        "breed_name": "Beagle",
        "gender": "Male",
        "from_age": 3.0,
        "to_age": 4.0,
        "avg_height_min": 40.0,
        "avg_height_max": 43.0,
        "avg_weight_min": 10.0,
        "avg_weight_max": 15.0,
        "avg_drink": 0.8,
        "avg_food": 1.5,
        "pic_url": "String"
    },
    {
        "breed_name": "Beagle",
        "gender": "Male",
        "from_age": 4.0,
        "to_age": 5.0,
        "avg_height_min": 41.0,
        "avg_height_max": 44.0,
        "avg_weight_min": 10.5,
        "avg_weight_max": 16.0,
        "avg_drink": 0.8,
        "avg_food": 1.6,
        "pic_url": "String"
    },
    {
        "breed_name": "Beagle",
        "gender": "Male",
        "from_age": 5.0,
        "to_age": 6.0,
        "avg_height_min": 41.0,
        "avg_height_max": 44.0,
        "avg_weight_min": 10.5,
        "avg_weight_max": 16.5,
        "avg_drink": 0.9,
        "avg_food": 1.7,
        "pic_url": "String"
    },
    {
        "breed_name": "Beagle",
        "gender": "Male",
        "from_age": 6.0,
        "to_age": 7.0,
        "avg_height_min": 41.0,
        "avg_height_max": 44.0,
        "avg_weight_min": 11.0,
        "avg_weight_max": 17.0,
        "avg_drink": 1.0,
        "avg_food": 1.8,
        "pic_url": "String"
    },
    {
        "breed_name": "Beagle",
        "gender": "Male",
        "from_age": 7.0,
        "to_age": 8.0,
        "avg_height_min": 41.0,
        "avg_height_max": 44.0,
        "avg_weight_min": 11.0,
        "avg_weight_max": 17.0,
        "avg_drink": 1.0,
        "avg_food": 1.8,
        "pic_url": "String"
    },
    {
        "breed_name": "Beagle",
        "gender": "Male",
        "from_age": 8.0,
        "to_age": 9.0,
        "avg_height_min": 41.0,
        "avg_height_max": 44.0,
        "avg_weight_min": 11.5,
        "avg_weight_max": 17.5,
        "avg_drink": 1.0,
        "avg_food": 1.9,
        "pic_url": "String"
    },
    {
        "breed_name": "Beagle",
        "gender": "Male",
        "from_age": 9.0,
        "to_age": 10.0,
        "avg_height_min": 41.0,
        "avg_height_max": 44.0,
        "avg_weight_min": 12.0,
        "avg_weight_max": 18.0,
        "avg_drink": 1.1,
        "avg_food": 2.0,
        "pic_url": "String"
    }

]
Beagel_Female=[
    {
        "breed_name": "Beagle",
        "gender": "Female",
        "from_age": 0.0,
        "to_age": 1.0,
        "avg_height_min": 30.0,
        "avg_height_max": 38.0,
        "avg_weight_min": 3.5,
        "avg_weight_max": 7.5,
        "avg_drink": 0.5,
        "avg_food": 1.0,
        "pic_url": "String"
    },
    {
        "breed_name": "Beagle",
        "gender": "Female",
        "from_age": 1.0,
        "to_age": 2.0,
        "avg_height_min": 38.0,
        "avg_height_max": 41.0,
        "avg_weight_min": 7.0,
        "avg_weight_max": 10.5,
        "avg_drink": 0.6,
        "avg_food": 1.2,
        "pic_url": "String"
    },
    {
        "breed_name": "Beagle",
        "gender": "Female",
        "from_age": 2.0,
        "to_age": 3.0,
        "avg_height_min": 40.0,
        "avg_height_max": 43.0,
        "avg_weight_min": 8.5,
        "avg_weight_max": 12.0,
        "avg_drink": 0.7,
        "avg_food": 1.3,
        "pic_url": "String"
    },
    {
        "breed_name": "Beagle",
        "gender": "Female",
        "from_age": 3.0,
        "to_age": 4.0,
        "avg_height_min": 40.0,
        "avg_height_max": 43.0,
        "avg_weight_min": 9.0,
        "avg_weight_max": 13.0,
        "avg_drink": 0.8,
        "avg_food": 1.4,
        "pic_url": "String"
    },
    {
        "breed_name": "Beagle",
        "gender": "Female",
        "from_age": 4.0,
        "to_age": 5.0,
        "avg_height_min": 41.0,
        "avg_height_max": 44.0,
        "avg_weight_min": 9.5,
        "avg_weight_max": 13.5,
        "avg_drink": 0.8,
        "avg_food": 1.5,
        "pic_url": "String"
    },
    {
        "breed_name": "Beagle",
        "gender": "Female",
        "from_age": 5.0,
        "to_age": 6.0,
        "avg_height_min": 41.0,
        "avg_height_max": 44.0,
        "avg_weight_min": 10.0,
        "avg_weight_max": 14.0,
        "avg_drink": 0.9,
        "avg_food": 1.6,
        "pic_url": "String"
    },
    {
        "breed_name": "Beagle",
        "gender": "Female",
        "from_age": 6.0,
        "to_age": 7.0,
        "avg_height_min": 41.0,
        "avg_height_max": 44.0,
        "avg_weight_min": 10.5,
        "avg_weight_max": 14.5,
        "avg_drink": 1.0,
        "avg_food": 1.7,
        "pic_url": "String"
    },
    {
        "breed_name": "Beagle",
        "gender": "Female",
        "from_age": 7.0,
        "to_age": 8.0,
        "avg_height_min": 41.0,
        "avg_height_max": 44.0,
        "avg_weight_min": 11.0,
        "avg_weight_max": 15.0,
        "avg_drink": 1.0,
        "avg_food": 1.8,
        "pic_url": "String"
    },
    {
        "breed_name": "Beagle",
        "gender": "Female",
        "from_age": 8.0,
        "to_age": 9.0,
        "avg_height_min": 41.0,
        "avg_height_max": 44.0,
        "avg_weight_min": 11.5,
        "avg_weight_max": 15.5,
        "avg_drink": 1.1,
        "avg_food": 1.9,
        "pic_url": "String"
    },
    {
        "breed_name": "Beagle",
        "gender": "Female",
        "from_age": 9.0,
        "to_age": 10.0,
        "avg_height_min": 41.0,
        "avg_height_max": 44.0,
        "avg_weight_min": 12.0,
        "avg_weight_max": 16.0,
        "avg_drink": 1.1,
        "avg_food": 2.0,
        "pic_url": "String"
    }
]
Boxer_Male=[
    {
        "breed_name": "Boxer",
        "gender": "Male",
        "from_age": 0.0,
        "to_age": 1.0,
        "avg_height_min": 53.0,
        "avg_height_max": 61.0,
        "avg_weight_min": 7.5,
        "avg_weight_max": 13.5,
        "avg_drink": 1.0,
        "avg_food": 2.0,
        "pic_url": "String"
    },
    {
        "breed_name": "Boxer",
        "gender": "Male",
        "from_age": 1.0,
        "to_age": 2.0,
        "avg_height_min": 56.0,
        "avg_height_max": 64.0,
        "avg_weight_min": 12.0,
        "avg_weight_max": 21.0,
        "avg_drink": 1.2,
        "avg_food": 2.2,
        "pic_url": "String"
    },
    {
        "breed_name": "Boxer",
        "gender": "Male",
        "from_age": 2.0,
        "to_age": 3.0,
        "avg_height_min": 58.0,
        "avg_height_max": 66.0,
        "avg_weight_min": 15.0,
        "avg_weight_max": 25.0,
        "avg_drink": 1.3,
        "avg_food": 2.4,
        "pic_url": "String"
    },
    {
        "breed_name": "Boxer",
        "gender": "Male",
        "from_age": 3.0,
        "to_age": 4.0,
        "avg_height_min": 59.0,
        "avg_height_max": 67.0,
        "avg_weight_min": 18.0,
        "avg_weight_max": 27.0,
        "avg_drink": 1.4,
        "avg_food": 2.5,
        "pic_url": "String"
    },
    {
        "breed_name": "Boxer",
        "gender": "Male",
        "from_age": 4.0,
        "to_age": 5.0,
        "avg_height_min": 60.0,
        "avg_height_max": 68.0,
        "avg_weight_min": 20.0,
        "avg_weight_max": 29.0,
        "avg_drink": 1.5,
        "avg_food": 2.6,
        "pic_url": "String"
    },
    {
        "breed_name": "Boxer",
        "gender": "Male",
        "from_age": 5.0,
        "to_age": 6.0,
        "avg_height_min": 60.0,
        "avg_height_max": 69.0,
        "avg_weight_min": 21.0,
        "avg_weight_max": 30.0,
        "avg_drink": 1.6,
        "avg_food": 2.7,
        "pic_url": "String"
    },
    {
        "breed_name": "Boxer",
        "gender": "Male",
        "from_age": 6.0,
        "to_age": 7.0,
        "avg_height_min": 60.0,
        "avg_height_max": 69.0,
        "avg_weight_min": 22.0,
        "avg_weight_max": 31.0,
        "avg_drink": 1.7,
        "avg_food": 2.8,
        "pic_url": "String"
    },
    {
        "breed_name": "Boxer",
        "gender": "Male",
        "from_age": 7.0,
        "to_age": 8.0,
        "avg_height_min": 60.0,
        "avg_height_max": 69.0,
        "avg_weight_min": 23.0,
        "avg_weight_max": 32.0,
        "avg_drink": 1.8,
        "avg_food": 2.9,
        "pic_url": "String"
    },
    {
        "breed_name": "Boxer",
        "gender": "Male",
        "from_age": 8.0,
        "to_age": 9.0,
        "avg_height_min": 60.0,
        "avg_height_max": 69.0,
        "avg_weight_min": 24.0,
        "avg_weight_max": 33.0,
        "avg_drink": 1.8,
        "avg_food": 3.0,
        "pic_url": "String"
    },
    {
        "breed_name": "Boxer",
        "gender": "Male",
        "from_age": 9.0,
        "to_age": 10.0,
        "avg_height_min": 60.0,
        "avg_height_max": 69.0,
        "avg_weight_min": 25.0,
        "avg_weight_max": 34.0,
        "avg_drink": 1.9,
        "avg_food": 3.1,
        "pic_url": "String"
    }
]
Boxer_Female=[
    {
        "breed_name": "Boxer",
        "gender": "Female",
        "from_age": 0.0,
        "to_age": 1.0,
        "avg_height_min": 51.0,
        "avg_height_max": 59.0,
        "avg_weight_min": 6.5,
        "avg_weight_max": 11.5,
        "avg_drink": 1.0,
        "avg_food": 1.9,
        "pic_url": "String"
    },
    {
        "breed_name": "Boxer",
        "gender": "Female",
        "from_age": 1.0,
        "to_age": 2.0,
        "avg_height_min": 54.0,
        "avg_height_max": 62.0,
        "avg_weight_min": 11.0,
        "avg_weight_max": 19.0,
        "avg_drink": 1.2,
        "avg_food": 2.0,
        "pic_url": "String"
    },
    {
        "breed_name": "Boxer",
        "gender": "Female",
        "from_age": 2.0,
        "to_age": 3.0,
        "avg_height_min": 56.0,
        "avg_height_max": 64.0,
        "avg_weight_min": 14.0,
        "avg_weight_max": 22.0,
        "avg_drink": 1.3,
        "avg_food": 2.2,
        "pic_url": "String"
    },
    {
        "breed_name": "Boxer",
        "gender": "Female",
        "from_age": 3.0,
        "to_age": 4.0,
        "avg_height_min": 57.0,
        "avg_height_max": 65.0,
        "avg_weight_min": 16.0,
        "avg_weight_max": 24.0,
        "avg_drink": 1.4,
        "avg_food": 2.3,
        "pic_url": "String"
    },
    {
        "breed_name": "Boxer",
        "gender": "Female",
        "from_age": 4.0,
        "to_age": 5.0,
        "avg_height_min": 58.0,
        "avg_height_max": 66.0,
        "avg_weight_min": 18.0,
        "avg_weight_max": 26.0,
        "avg_drink": 1.5,
        "avg_food": 2.5,
        "pic_url": "String"
    },
    {
        "breed_name": "Boxer",
        "gender": "Female",
        "from_age": 5.0,
        "to_age": 6.0,
        "avg_height_min": 59.0,
        "avg_height_max": 67.0,
        "avg_weight_min": 19.0,
        "avg_weight_max": 28.0,
        "avg_drink": 1.6,
        "avg_food": 2.6,
        "pic_url": "String"
    },
    {
        "breed_name": "Boxer",
        "gender": "Female",
        "from_age": 6.0,
        "to_age": 7.0,
        "avg_height_min": 59.0,
        "avg_height_max": 68.0,
        "avg_weight_min": 20.0,
        "avg_weight_max": 29.0,
        "avg_drink": 1.7,
        "avg_food": 2.7,
        "pic_url": "String"
    },
    {
        "breed_name": "Boxer",
        "gender": "Female",
        "from_age": 7.0,
        "to_age": 8.0,
        "avg_height_min": 59.0,
        "avg_height_max": 68.0,
        "avg_weight_min": 21.0,
        "avg_weight_max": 30.0,
        "avg_drink": 1.8,
        "avg_food": 2.8,
        "pic_url": "String"
    },
    {
        "breed_name": "Boxer",
        "gender": "Female",
        "from_age": 8.0,
        "to_age": 9.0,
        "avg_height_min": 59.0,
        "avg_height_max": 68.0,
        "avg_weight_min": 22.0,
        "avg_weight_max": 31.0,
        "avg_drink": 1.8,
        "avg_food": 2.9,
        "pic_url": "String"
    },
    {
        "breed_name": "Boxer",
        "gender": "Female",
        "from_age": 9.0,
        "to_age": 10.0,
        "avg_height_min": 59.0,
        "avg_height_max": 68.0,
        "avg_weight_min": 23.0,
        "avg_weight_max": 32.0,
        "avg_drink": 1.9,
        "avg_food": 3.0,
        "pic_url": "String"
    }
]
French_Bulldog_Male=[
    {
        "breed_name": "French Bulldog",
        "gender": "Male",
        "from_age": 0.0,
        "to_age": 1.0,
        "avg_height_min": 25.0,
        "avg_height_max": 30.0,
        "avg_weight_min": 4.0,
        "avg_weight_max": 6.0,
        "avg_drink": 0.4,
        "avg_food": 0.8,
        "pic_url": "String"
    },
    {
        "breed_name": "French Bulldog",
        "gender": "Male",
        "from_age": 1.0,
        "to_age": 2.0,
        "avg_height_min": 30.0,
        "avg_height_max": 35.0,
        "avg_weight_min": 6.0,
        "avg_weight_max": 8.0,
        "avg_drink": 0.5,
        "avg_food": 1.0,
        "pic_url": "String"
    },
    {
        "breed_name": "French Bulldog",
        "gender": "Male",
        "from_age": 2.0,
        "to_age": 3.0,
        "avg_height_min": 30.0,
        "avg_height_max": 35.0,
        "avg_weight_min": 7.0,
        "avg_weight_max": 9.0,
        "avg_drink": 0.6,
        "avg_food": 1.2,
        "pic_url": "String"
    },
    {
        "breed_name": "French Bulldog",
        "gender": "Male",
        "from_age": 3.0,
        "to_age": 4.0,
        "avg_height_min": 30.0,
        "avg_height_max": 35.0,
        "avg_weight_min": 8.0,
        "avg_weight_max": 10.0,
        "avg_drink": 0.7,
        "avg_food": 1.3,
        "pic_url": "String"
    },
    {
        "breed_name": "French Bulldog",
        "gender": "Male",
        "from_age": 4.0,
        "to_age": 5.0,
        "avg_height_min": 30.0,
        "avg_height_max": 35.0,
        "avg_weight_min": 8.5,
        "avg_weight_max": 11.0,
        "avg_drink": 0.7,
        "avg_food": 1.4,
        "pic_url": "String"
    },
    {
        "breed_name": "French Bulldog",
        "gender": "Male",
        "from_age": 5.0,
        "to_age": 6.0,
        "avg_height_min": 30.0,
        "avg_height_max": 35.0,
        "avg_weight_min": 9.0,
        "avg_weight_max": 11.5,
        "avg_drink": 0.8,
        "avg_food": 1.5,
        "pic_url": "String"
    },
    {
        "breed_name": "French Bulldog",
        "gender": "Male",
        "from_age": 6.0,
        "to_age": 7.0,
        "avg_height_min": 30.0,
        "avg_height_max": 35.0,
        "avg_weight_min": 9.5,
        "avg_weight_max": 12.0,
        "avg_drink": 0.8,
        "avg_food": 1.6,
        "pic_url": "String"
    },
    {
        "breed_name": "French Bulldog",
        "gender": "Male",
        "from_age": 7.0,
        "to_age": 8.0,
        "avg_height_min": 30.0,
        "avg_height_max": 35.0,
        "avg_weight_min": 10.0,
        "avg_weight_max": 12.5,
        "avg_drink": 0.9,
        "avg_food": 1.7,
        "pic_url": "String"
    },
    {
        "breed_name": "French Bulldog",
        "gender": "Male",
        "from_age": 8.0,
        "to_age": 9.0,
        "avg_height_min": 30.0,
        "avg_height_max": 35.0,
        "avg_weight_min": 10.5,
        "avg_weight_max": 13.0,
        "avg_drink": 0.9,
        "avg_food": 1.8,
        "pic_url": "String"
    },
    {
        "breed_name": "French Bulldog",
        "gender": "Male",
        "from_age": 9.0,
        "to_age": 10.0,
        "avg_height_min": 30.0,
        "avg_height_max": 35.0,
        "avg_weight_min": 11.0,
        "avg_weight_max": 13.5,
        "avg_drink": 1.0,
        "avg_food": 1.9,
        "pic_url": "String"
    }
]
French_Bulldog_Female=[
    {
        "breed_name": "French Bulldog",
        "gender": "Female",
        "from_age": 0.0,
        "to_age": 1.0,
        "avg_height_min": 25.0,
        "avg_height_max": 30.0,
        "avg_weight_min": 4.0,
        "avg_weight_max": 6.0,
        "avg_drink": 0.4,
        "avg_food": 0.8,
        "pic_url": "String"
    },
    {
        "breed_name": "French Bulldog",
        "gender": "Female",
        "from_age": 1.0,
        "to_age": 2.0,
        "avg_height_min": 30.0,
        "avg_height_max": 35.0,
        "avg_weight_min": 6.0,
        "avg_weight_max": 8.0,
        "avg_drink": 0.5,
        "avg_food": 1.0,
        "pic_url": "String"
    },
    {
        "breed_name": "French Bulldog",
        "gender": "Female",
        "from_age": 2.0,
        "to_age": 3.0,
        "avg_height_min": 30.0,
        "avg_height_max": 35.0,
        "avg_weight_min": 7.0,
        "avg_weight_max": 9.0,
        "avg_drink": 0.6,
        "avg_food": 1.2,
        "pic_url": "String"
    },
    {
        "breed_name": "French Bulldog",
        "gender": "Female",
        "from_age": 3.0,
        "to_age": 4.0,
        "avg_height_min": 30.0,
        "avg_height_max": 35.0,
        "avg_weight_min": 8.0,
        "avg_weight_max": 10.0,
        "avg_drink": 0.7,
        "avg_food": 1.3,
        "pic_url": "String"
    },
    {
        "breed_name": "French Bulldog",
        "gender": "Female",
        "from_age": 4.0,
        "to_age": 5.0,
        "avg_height_min": 30.0,
        "avg_height_max": 35.0,
        "avg_weight_min": 8.5,
        "avg_weight_max": 10.5,
        "avg_drink": 0.7,
        "avg_food": 1.4,
        "pic_url": "String"
    },
    {
        "breed_name": "French Bulldog",
        "gender": "Female",
        "from_age": 5.0,
        "to_age": 6.0,
        "avg_height_min": 30.0,
        "avg_height_max": 35.0,
        "avg_weight_min": 9.0,
        "avg_weight_max": 11.0,
        "avg_drink": 0.8,
        "avg_food": 1.5,
        "pic_url": "String"
    },
    {
        "breed_name": "French Bulldog",
        "gender": "Female",
        "from_age": 6.0,
        "to_age": 7.0,
        "avg_height_min": 30.0,
        "avg_height_max": 35.0,
        "avg_weight_min": 9.5,
        "avg_weight_max": 11.5,
        "avg_drink": 0.8,
        "avg_food": 1.6,
        "pic_url": "String"
    },
    {
        "breed_name": "French Bulldog",
        "gender": "Female",
        "from_age": 7.0,
        "to_age": 8.0,
        "avg_height_min": 30.0,
        "avg_height_max": 35.0,
        "avg_weight_min": 10.0,
        "avg_weight_max": 12.0,
        "avg_drink": 0.9,
        "avg_food": 1.7,
        "pic_url": "String"
    },
    {
        "breed_name": "French Bulldog",
        "gender": "Female",
        "from_age": 8.0,
        "to_age": 9.0,
        "avg_height_min": 30.0,
        "avg_height_max": 35.0,
        "avg_weight_min": 10.5,
        "avg_weight_max": 12.5,
        "avg_drink": 0.9,
        "avg_food": 1.8,
        "pic_url": "String"
    },
    {
        "breed_name": "French Bulldog",
        "gender": "Female",
        "from_age": 9.0,
        "to_age": 10.0,
        "avg_height_min": 30.0,
        "avg_height_max": 35.0,
        "avg_weight_min": 11.0,
        "avg_weight_max": 13.0,
        "avg_drink": 1.0,
        "avg_food": 1.9,
        "pic_url": "String"
    }
]
Poodle_Male = [
    {
        "breed_name": "Poodle",
        "gender": "Male",
        "from_age": 0.0,
        "to_age": 1.0,
        "avg_height_min": 30.0,
        "avg_height_max": 35.0,
        "avg_weight_min": 4.0,
        "avg_weight_max": 6.0,
        "avg_drink": 0.5,
        "avg_food": 1.0,
        "pic_url": "String"
    },
    {
        "breed_name": "Poodle",
        "gender": "Male",
        "from_age": 1.0,
        "to_age": 2.0,
        "avg_height_min": 35.0,
        "avg_height_max": 40.0,
        "avg_weight_min": 6.0,
        "avg_weight_max": 9.0,
        "avg_drink": 0.6,
        "avg_food": 1.2,
        "pic_url": "String"
    },
    {
        "breed_name": "Poodle",
        "gender": "Male",
        "from_age": 2.0,
        "to_age": 3.0,
        "avg_height_min": 35.0,
        "avg_height_max": 45.0,
        "avg_weight_min": 7.0,
        "avg_weight_max": 10.0,
        "avg_drink": 0.7,
        "avg_food": 1.4,
        "pic_url": "String"
    },
    {
        "breed_name": "Poodle",
        "gender": "Male",
        "from_age": 3.0,
        "to_age": 4.0,
        "avg_height_min": 35.0,
        "avg_height_max": 45.0,
        "avg_weight_min": 8.0,
        "avg_weight_max": 11.0,
        "avg_drink": 0.8,
        "avg_food": 1.5,
        "pic_url": "String"
    },
    {
        "breed_name": "Poodle",
        "gender": "Male",
        "from_age": 4.0,
        "to_age": 5.0,
        "avg_height_min": 35.0,
        "avg_height_max": 45.0,
        "avg_weight_min": 8.5,
        "avg_weight_max": 11.5,
        "avg_drink": 0.8,
        "avg_food": 1.6,
        "pic_url": "String"
    },
    {
        "breed_name": "Poodle",
        "gender": "Male",
        "from_age": 5.0,
        "to_age": 6.0,
        "avg_height_min": 35.0,
        "avg_height_max": 45.0,
        "avg_weight_min": 9.0,
        "avg_weight_max": 12.0,
        "avg_drink": 0.9,
        "avg_food": 1.7,
        "pic_url": "String"
    },
    {
        "breed_name": "Poodle",
        "gender": "Male",
        "from_age": 6.0,
        "to_age": 7.0,
        "avg_height_min": 35.0,
        "avg_height_max": 45.0,
        "avg_weight_min": 9.5,
        "avg_weight_max": 12.5,
        "avg_drink": 0.9,
        "avg_food": 1.8,
        "pic_url": "String"
    },
    {
        "breed_name": "Poodle",
        "gender": "Male",
        "from_age": 7.0,
        "to_age": 8.0,
        "avg_height_min": 35.0,
        "avg_height_max": 45.0,
        "avg_weight_min": 10.0,
        "avg_weight_max": 13.0,
        "avg_drink": 1.0,
        "avg_food": 1.9,
        "pic_url": "String"
    },
    {
        "breed_name": "Poodle",
        "gender": "Male",
        "from_age": 8.0,
        "to_age": 9.0,
        "avg_height_min": 35.0,
        "avg_height_max": 45.0,
        "avg_weight_min": 10.5,
        "avg_weight_max": 13.5,
        "avg_drink": 1.0,
        "avg_food": 2.0,
        "pic_url": "String"
    },
    {
        "breed_name": "Poodle",
        "gender": "Male",
        "from_age": 9.0,
        "to_age": 10.0,
        "avg_height_min": 35.0,
        "avg_height_max": 45.0,
        "avg_weight_min": 11.0,
        "avg_weight_max": 14.0,
        "avg_drink": 1.1,
        "avg_food": 2.1,
        "pic_url": "String"
    }
]
Poodle_Female = [
    {
        "breed_name": "Poodle",
        "gender": "Female",
        "from_age": 0.0,
        "to_age": 1.0,
        "avg_height_min": 28.0,
        "avg_height_max": 33.0,
        "avg_weight_min": 3.5,
        "avg_weight_max": 5.5,
        "avg_drink": 0.4,
        "avg_food": 0.9,
        "pic_url": "String"
    },
    {
        "breed_name": "Poodle",
        "gender": "Female",
        "from_age": 1.0,
        "to_age": 2.0,
        "avg_height_min": 33.0,
        "avg_height_max": 38.0,
        "avg_weight_min": 5.5,
        "avg_weight_max": 8.0,
        "avg_drink": 0.5,
        "avg_food": 1.0,
        "pic_url": "String"
    },
    {
        "breed_name": "Poodle",
        "gender": "Female",
        "from_age": 2.0,
        "to_age": 3.0,
        "avg_height_min": 33.0,
        "avg_height_max": 42.0,
        "avg_weight_min": 6.0,
        "avg_weight_max": 9.0,
        "avg_drink": 0.6,
        "avg_food": 1.2,
        "pic_url": "String"
    },
    {
        "breed_name": "Poodle",
        "gender": "Female",
        "from_age": 3.0,
        "to_age": 4.0,
        "avg_height_min": 33.0,
        "avg_height_max": 42.0,
        "avg_weight_min": 6.5,
        "avg_weight_max": 9.5,
        "avg_drink": 0.7,
        "avg_food": 1.3,
        "pic_url": "String"
    },
    {
        "breed_name": "Poodle",
        "gender": "Female",
        "from_age": 4.0,
        "to_age": 5.0,
        "avg_height_min": 33.0,
        "avg_height_max": 42.0,
        "avg_weight_min": 7.0,
        "avg_weight_max": 10.0,
        "avg_drink": 0.7,
        "avg_food": 1.4,
        "pic_url": "String"
    },
    {
        "breed_name": "Poodle",
        "gender": "Female",
        "from_age": 5.0,
        "to_age": 6.0,
        "avg_height_min": 33.0,
        "avg_height_max": 42.0,
        "avg_weight_min": 7.5,
        "avg_weight_max": 10.5,
        "avg_drink": 0.8,
        "avg_food": 1.5,
        "pic_url": "String"
    },
    {
        "breed_name": "Poodle",
        "gender": "Female",
        "from_age": 6.0,
        "to_age": 7.0,
        "avg_height_min": 33.0,
        "avg_height_max": 42.0,
        "avg_weight_min": 8.0,
        "avg_weight_max": 11.0,
        "avg_drink": 0.8,
        "avg_food": 1.6,
        "pic_url": "String"
    },
    {
        "breed_name": "Poodle",
        "gender": "Female",
        "from_age": 7.0,
        "to_age": 8.0,
        "avg_height_min": 33.0,
        "avg_height_max": 42.0,
        "avg_weight_min": 8.5,
        "avg_weight_max": 11.5,
        "avg_drink": 0.9,
        "avg_food": 1.7,
        "pic_url": "String"
    },
    {
        "breed_name": "Poodle",
        "gender": "Female",
        "from_age": 8.0,
        "to_age": 9.0,
        "avg_height_min": 33.0,
        "avg_height_max": 42.0,
        "avg_weight_min": 9.0,
        "avg_weight_max": 12.0,
        "avg_drink": 0.9,
        "avg_food": 1.8,
        "pic_url": "String"
    },
    {
        "breed_name": "Poodle",
        "gender": "Female",
        "from_age": 9.0,
        "to_age": 10.0,
        "avg_height_min": 33.0,
        "avg_height_max": 42.0,
        "avg_weight_min": 9.5,
        "avg_weight_max": 12.5,
        "avg_drink": 1.0,
        "avg_food": 1.9,
        "pic_url": "String"
    }
]


mock_data = [Labrador_Retriever_Male,Labrador_Retriever_Female,Golden_Retriever_Male,
Golden_Retriever_Female,
Beagel_Male,
Beagel_Female,
Boxer_Male,
Boxer_Female,
French_Bulldog_Male,
French_Bulldog_Female,
Poodle_Male,
Poodle_Female]

def populate_db():
    db = db = MongoConnectionHolder.get_db()
    if db is None:
        print("Failed to connect to the database")
        return
    for mock in mock_data:
        for data in mock:
            collection_name = data['breed_name']
            collection = db[collection_name]
            data["_id"] = str(uuid.uuid4())
            data["created_at"] = datetime.now()
            data["updated_at"] = datetime.now()
            try:
                collection.insert_one(data)
                print(f"Inserted data for {data['breed_name']} ({data['gender']})")
            except Exception as e:
                print(f"Error inserting data for {data['breed_name']}: {e}")

if __name__ == "__main__":
    populate_db()